name: Fetch Weather JSON

on:
  schedule:
    - cron: "0 * * * *"  # Once per hour
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch weather from RapidAPI
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          curl -s -H "x-rapidapi-key: $RAPIDAPI_KEY" \
               -H "x-rapidapi-host: weatherapi-com.p.rapidapi.com" \
               "https://weatherapi-com.p.rapidapi.com/current.json?q=Kuala Lumpur" \
               -o weather.json

      - name: Commit and push weather.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add weather.json
          git diff --cached --quiet || git commit -m "Update weather.json"
          git push https://x-access-token:${GH_TOKEN}@github.com/Z-Fikri17/alpineclock.git main
